from module import (
    random_user_id,
    user_id_gen_by_user,
    rgb_color_gen,
    list_of_hexa_colors,
    list_of_rgb_colors,
    generate_colors,
    shuffle_list
)

print("Create random user id")
print(random_user_id())

print("\nID generated by user ")
print(user_id_gen_by_user())

print("\nGenerated RGB Color")
print(rgb_color_gen())

print("\nGenerated list of hexadecimal colors ")
print(list_of_hexa_colors())

print("\nGenerated list of hexadecimal colors ")
print(list_of_rgb_colors(5))

print("\nGenerated list of hex and rgb colors")
print(generate_colors("rgb", 4))

print("\nShuffle list")
print(shuffle_list([51, 62, 28, 14, 32]))
