# Day 12: 30 Days of python programming

from random import choice, randint
import string

print("Create random user id")
def random_user_id():
    characters = string.ascii_letters + string.digits
    user_id = ""

    for i in range(6):
        user_id += choice(characters)

    return user_id


print(random_user_id())


print("\nID generated by user ")
def user_id_gen_by_user():
    number_of_characters = int(input("Entre number of characters : "))
    number_of_id_to_gen = int(input("Enter number of ID to be generated : "))
    characters = string.ascii_letters + string.digits
    i = 0

    while i < number_of_id_to_gen:
        user_id = ""

        for _ in range(number_of_characters):
            user_id += choice(characters)

        i += 1
        print(user_id)


user_id_gen_by_user()


print("\nGenerated RGB Color")
def rgb_color_gen():
    rgb_color = []

    for i in range(3):
        rgb_color.append(randint(0, 255))

    rgb_color = tuple(rgb_color)

    return rgb_color


print(rgb_color_gen())


print("\nGenerated list of hexadecimal colors ")
def list_of_hexa_colors():
    characters = string.ascii_letters[:6] + string.digits

    hexa_colors = "#"

    for _ in range(6):
        hexa_colors += choice(characters)

    return hexa_colors


print(list_of_hexa_colors())


print("\nGenerated list of hexadecimal colors ")
def list_of_rgb_colors(nb):
    list_rgb_colors = []

    for _ in range(nb):
        rgb_colors = []

        for _ in range(3):
            rgb_colors.append(randint(0, 255))

        list_rgb_colors.append(f"rgb{tuple(rgb_colors)}")

    return list_rgb_colors


print(list_of_rgb_colors(5))


print("\nGenerated list of hex and rgb colors")
def generate_colors(color_type, color_number):
    if color_type == 'hexa':
        list_hexa_colors = []
        for _ in range(color_number):
            list_hexa_colors.append(list_of_hexa_colors())

        return list_hexa_colors

    elif color_type == 'rgb':
        return list_of_rgb_colors(color_number)

    return None


print(generate_colors("rgb", 4))



print("\nShuffle list")
def shuffle_list(list_n):
    list_shuffle = []
    for l in range(len(list_n)):
        list_shuffle.append(choice(list_n))

    return list_shuffle


print(shuffle_list([51, 62, 28, 14, 32]))