# Day 12: 30 Days of python programming

from random import choice, randint
import string

print("Create random user id")


def random_user_id():
    characters = string.ascii_letters + string.digits
    user_id = ""

    for i in range(6):
        user_id += choice(characters)

    return user_id


print(random_user_id())

print("\nID generated by user ")


def user_id_gen_by_user():
    number_of_characters = int(input("Entre number of characters : "))
    number_of_id_to_gen = int(input("Enter number of ID to be generated : "))
    characters = string.ascii_letters + string.digits
    i = 0

    while i < number_of_id_to_gen:
        user_id = ""

        for _ in range(number_of_characters):
            user_id += choice(characters)

        i += 1
        print(user_id)


user_id_gen_by_user()

print("\nGenerated RGB Color")


def rgb_color_gen():
    rgb_color = []

    for i in range(3):
        rgb_color.append(randint(0, 255))

    rgb_color = tuple(rgb_color)

    return rgb_color


print(rgb_color_gen())
